export enum CallRecordsEvents {
  SET_RECORDS = 'SET_RECORDS',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SORTING = 'SET_SORTING',
  SET_DATE_INTERVAL = 'SET_DATE_INTERVAL',
  DELETE_RECORD = 'DELETE_RECORD',
  SET_CALL_DIRECTION = 'SET_CALL_DIRECTION',
}
