export enum CallRecordsEvents {
  SET_RECORDS = 'SET_RECORDS',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SORTING = 'SET_SORTING',
  SET_DATE_INTERVAL = 'SET_DATE_INTERVAL',
  SET_CALL_DIRECTION = 'SET_CALL_DIRECTION',
  REQUEST_RECORDS = 'REQUEST_RECORDS',
  REQUEST_RECORDS_SUCCESS = 'REQUEST_RECORDS_SUCCESS',
  REQUEST_RECORDS_FAIL = 'REQUEST_RECORDS_FAIL',
  DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST',
  DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS',
  DELETE_RECORD_FAIL = 'DELETE_RECORD_FAIL',
}
